spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_scoring
    username: bank_user
    password: bank_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

grpc:
  server:
    port: 9090

logging:
  level:
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
